---
title: "Sistema de diagnóstico y selección para favorecer la permanencia en la educación superior de estudiantes provenientes de establecimientos altamente vulnerables"
subtitle:  Fondef (2016-2018).
summary: ""
tags:
- Fondef
date: "2021-03-31T00:00:00Z"
show_date: false
# Optional external URL for project (replaces project detail page).
external_link: ""
featured: true
image:
#  caption: Photo by rawpixel on Unsplash
  focal_point: Smart

links:
- icon: graduation-cap 
  icon_pack: fa 
  name: Repositorio ANID
  url:  https://repositorio.anid.cl/entities/proyecto/2af3c3fd-be5c-4a64-a582-4db2ebec12b9?spc.sf=score&spc.sd=DESC
#- icon: twitter
#  icon_pack: fab
#  name: Follow
#  url: https://twitter.com/georgecushen
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""

# Slides (optional).
#   Associate this project with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides = "example-slides"` references `content/slides/example-slides.md`.
#   Otherwise, set `slides = ""`.
#slides: example
authors: ["ClaudiaZuniga"]
---

El proyecto propone adaptar y validar para estudiantes secundarios de liceos de alta vulnerabilidad, de distinta rama educacional y de distintas regiones, un conjunto de instrumentos psicométricos que permiten el diagnóstico de variables asociadas a una adecuada transición a la educación superior. Estos test se aplican en formato online mediante una plataforma Web que entrega un informe individual de forma automatizada, permitiendo que el sistema de diagnóstico esté disponible para cualquier liceo con conexión a Internet. Se realizará además la adaptación y validación de un test de Intereses Profesionales para su uso con fines de selección, en el marco del Programa PACE.


**Periodo**: 2016-2018

**Facultad**: Ciencias Sociales

**Departamento**: Psicología

