---
title: "CVN-LogisTIC: Herramientas asociativas inteligentes de negociación y decisión para el desarrollo de un Port Community System"
subtitle:  Fondef (2019-2021).
summary: ""
tags:
- Fondef
date: "2021-03-31T00:00:00Z"
show_date: false
# Optional external URL for project (replaces project detail page).
external_link: ""
featured: true
image:
#  caption: Photo by rawpixel on Unsplash
  focal_point: Smart

links:
- icon: graduation-cap 
  icon_pack: fa 
  name: Formulación proyecto 
  url:  project/fondef/cvn-logistic/fondef_ID19I10075.pdf
#- icon: twitter
#  icon_pack: fab
#  name: Follow
#  url: https://twitter.com/georgecushen
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""

# Slides (optional).
#   Associate this project with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides = "example-slides"` references `content/slides/example-slides.md`.
#   Otherwise, set `slides = ""`.
#slides: example
authors: ["RodrigoFigueroa"]
---

FONDEF ID19I10075 tuvo como objetivo desarrollar herramientas asociativas e inteligentes de negociación y decisión para el fortalecimiento de comunidades logísticas y la emergencia de soluciones de base tecnológica para la coordinación, tales como Port Comunnity System (PCS) o Air Cargo Community System (CCS). El Proyecto se basa en un estudio de caso referido a la experiencia de la Asociación de Transporte Express (ATREX) y su Centro Logístico de la Industria del Courier, ubicado en el Aeropuerto de Santiago. El Proyecto constata que ATREX y su Centro Logístico eran una experiencia exitosa de gobernanza colaborativa en un sistema complejo (compuesto por actores privados y públicos) que posibilitan un uso intensivo de soluciones de base tecnológica, que incrementaron la trazabilidad, la transparencia y la agilidad de las operaciones logísticas, a la vez que mejoran el cumplimiento normativo asociado a estas operaciones. Los principales resultados de esta forma de gobernanza y optimización de la coordinación entre componentes de un sistema complejo fueron la reducción de los costos operacionales para las empresas y servicios públicos, una mayor eficiencia en las operaciones logísticas, especialmente en la gestión del tiempo, y la adaptación de la industria del Courier a los efectos de la pandemia y la rápida expansión del e-commerce. 


**Periodo**: 2019-2021

**Facultad**: Ciencias Sociales

**Departamento**: Sociología

